language: php
php:
  - nightly
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

sudo: false

addons:
  postgresql: "9.3"
  mariadb: '10.0'


# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - mysql -e "create database IF NOT EXISTS test1;" -uroot
  - psql -c 'create database travis_ci_test;' -U postgres
  - if [[ $(phpenv version-name) =~ 5.[3456] ]] ; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $(phpenv version-name) =~ 5.[3456] ]] ; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $(phpenv version-name) =~ 5.[3456] ]] ; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - cp -rf tests/conf.travis.php tests/conf.php
  - composer install --dev --no-interaction

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -v --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
 - if [[ $(phpenv version-name) =~ 5.[3456] ]] ; then php vendor/bin/coveralls -v; fi
 - if [[ $(phpenv version-name) =~ 5.[3456] ]] ; then CODECLIMATE_REPO_TOKEN=bef21a7b3d0a531fec57b713df1720bb0da7114f5ce33a3e492ce9599b8ac8df ./vendor/bin/test-reporter; fi

cache:
  directories:
    - $HOME/.composer/cache
