language: php
php:
  - nightly
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

sudo: false

addons:
  postgresql: "9.3"
  mariadb: '10.0'


# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - mysql -e "create database IF NOT EXISTS test1;" -uroot
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp -rf tests/conf.travis.php tests/conf.php
  - composer install --dev --no-interaction
  - cat composer.lock

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

script:
  - mkdir -p build/logs
  #- ./vendor/bin/phpunit -v --configuration phpunit.xml --coverage-clover build/logs/clover.xml
  - php -dxdebug.coverage_enable=1 ./vendor/bin/phpunit --coverage-text



cache:
  directories:
    - $HOME/.composer/cache
